import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Layout, NavStrip } from "@/components";
import { CartProvider } from "@/hooks/useCart";
import { AuthProvider } from "@/hooks/useAuth";

const poppins = Poppins({ subsets: ["latin"], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>
        <main>
          <AuthProvider>
            <CartProvider>
              <Toaster toastOptions={{
                style: {
                  backgroundColor: 'rgb(51 65 85)',
                  color: '#fff',
                }
              }} />
              <Layout>
                <div className="flex-grow">
                  {children}
                </div>
              </Layout>
            </CartProvider>
          </AuthProvider>
        </main>
      </body>
    </html >
  );
}
